#!/bin/bash
#
# This script keeps nginx correctly configured when running behind Cloudflare.
#
# Cloudflare proxies all incoming requests, so without this configuration
# nginx would see every client as a Cloudflare IP instead of the real visitor.
#
# The script:
#   - Downloads Cloudflare's current IPv4 and IPv6 ranges
#   - Generates an nginx include file with `set_real_ip_from` entries
#   - Configures nginx to trust the `CF-Connecting-IP` header
#   - Generates a second include file with matching `allow` entries, for a
#     server block that wants to refuse anything not arriving via Cloudflare
#   - Reloads nginx after verifying the configuration
#
# It is intended to be run from cron so Cloudflare IP changes are picked up
# automatically and logs, rate limiting, and access controls continue to
# see real client IP addresses.
#
# ---------------------------------------------------------------------------
# Why there are two files
# ---------------------------------------------------------------------------
#
# `set_real_ip_from` and `allow` answer different questions from the same list.
# The first says "a request relayed by this address is telling the truth about
# who sent it"; the second says "this address may connect at all". A host can
# want the first without the second — that is every deployment that proxies
# through Cloudflare but still expects to be reachable directly — so they are
# written separately and included separately.
#
# **The allow file contains no `deny`, deliberately.** The rule that closes the
# door belongs in the server block next to the local exceptions it sits with, so
# that this generated file can be rewritten, truncated or deleted without that
# being the same event as locking everybody out. See nginx.conf.example.
#

set -euo pipefail

CLOUDFLARE_FILE_PATH="${1:-/etc/nginx/cloudflare}"
ALLOW_FILE_PATH="${2:-/etc/nginx/cloudflare-allow}"

# Cloudflare has published somewhere around twenty ranges for years. This is not
# a guess at the right number, it is a floor: a truncated download or a
# reformatted endpoint should stop the script rather than quietly narrow the set
# of addresses nginx will accept, which is a lockout.
MIN_EXPECTED_RANGES=10

ipv4="$(curl -fsSL https://www.cloudflare.com/ips-v4)"
ipv6="$(curl -fsSL https://www.cloudflare.com/ips-v6)"

# Fetched once into variables rather than curled per output file, so the two
# files cannot disagree because the list changed between two requests.
ranges="$(printf '%s\n%s\n' "$ipv4" "$ipv6" | grep -c '[^[:space:]]')"

if [[ "$ranges" -lt "$MIN_EXPECTED_RANGES" ]]; then
    echo "Refusing to write: only $ranges Cloudflare ranges fetched, expected at least $MIN_EXPECTED_RANGES" >&2
    exit 1
fi

real_ip_tmp="$(mktemp)"
allow_tmp="$(mktemp)"
trap 'rm -f "$real_ip_tmp" "$allow_tmp"' EXIT

# Trust the forwarded client address from these, and nothing else.
{
    echo "# Cloudflare — generated by cloudflare-sync-ips.sh, do not edit"
    echo ""
    echo "# - IPv4"
    printf '%s\n' "$ipv4" | grep '[^[:space:]]' | while read -r ip; do
        echo "set_real_ip_from $ip;"
    done

    echo ""
    echo "# - IPv6"
    printf '%s\n' "$ipv6" | grep '[^[:space:]]' | while read -r ip; do
        echo "set_real_ip_from $ip;"
    done

    echo ""
    echo "real_ip_header CF-Connecting-IP;"
} > "$real_ip_tmp"

# Accept a connection from these. No `deny` here — see the note at the top.
{
    echo "# Cloudflare — generated by cloudflare-sync-ips.sh, do not edit"
    echo "#"
    echo "# Include this where an origin should only answer Cloudflare, then add"
    echo "# any local exceptions and a closing 'deny all;' in the server block."
    echo ""
    echo "# - IPv4"
    printf '%s\n' "$ipv4" | grep '[^[:space:]]' | while read -r ip; do
        echo "allow $ip;"
    done

    echo ""
    echo "# - IPv6"
    printf '%s\n' "$ipv6" | grep '[^[:space:]]' | while read -r ip; do
        echo "allow $ip;"
    done
} > "$allow_tmp"

# Keep what is currently in place, so a configuration this breaks can be undone
# before nginx is asked to run with it.
previous_real_ip="$(mktemp)"
previous_allow="$(mktemp)"
trap 'rm -f "$real_ip_tmp" "$allow_tmp" "$previous_real_ip" "$previous_allow"' EXIT
[[ -f "$CLOUDFLARE_FILE_PATH" ]] && cp -a "$CLOUDFLARE_FILE_PATH" "$previous_real_ip"
[[ -f "$ALLOW_FILE_PATH" ]] && cp -a "$ALLOW_FILE_PATH" "$previous_allow"

install -m 0644 "$real_ip_tmp" "$CLOUDFLARE_FILE_PATH"
install -m 0644 "$allow_tmp" "$ALLOW_FILE_PATH"

# Test, and put the old files back if the new ones do not survive it. Reloading
# is the easy half; the half worth writing down is that a bad allow list is an
# outage, so it never gets as far as a running nginx.
if ! nginx -t; then
    echo "nginx rejected the generated files; restoring the previous ones" >&2
    [[ -s "$previous_real_ip" ]] && install -m 0644 "$previous_real_ip" "$CLOUDFLARE_FILE_PATH"
    [[ -s "$previous_allow" ]] && install -m 0644 "$previous_allow" "$ALLOW_FILE_PATH"
    exit 1
fi

systemctl reload nginx
