#!/bin/bash
#
# This script keeps nginx correctly configured when running behind Cloudflare.
#
# Cloudflare proxies all incoming requests, so without this configuration
# nginx would see every client as a Cloudflare IP instead of the real visitor.
#
# The script:
#   - Downloads Cloudflare's current IPv4 and IPv6 ranges
#   - Generates an nginx include file with `set_real_ip_from` entries
#   - Configures nginx to trust the `CF-Connecting-IP` header
#   - Generates a second include file, in `geo` map form, for an origin that
#     wants to refuse anything not arriving via Cloudflare
#   - Reloads nginx after verifying the configuration
#
# It is intended to be run from cron so Cloudflare IP changes are picked up
# automatically and logs, rate limiting, and access controls continue to
# see real client IP addresses.
#
# ---------------------------------------------------------------------------
# Why there are two files
# ---------------------------------------------------------------------------
#
# `set_real_ip_from` and the guard list answer different questions from the same
# ranges. The first says "a request relayed by this address is telling the truth
# about who sent it"; the second says "this address may connect at all". A host
# can want the first without the second — that is every deployment that proxies
# through Cloudflare but still expects to be reachable directly.
#
# ---------------------------------------------------------------------------
# Why the guard file is a `geo` map and not a list of `allow` rules
# ---------------------------------------------------------------------------
#
# **Because `allow` would deny everybody, and it would look like it was working
# right up until it did.** `allow`/`deny` test `$remote_addr`, and the realip
# module rewrites `$remote_addr` from `CF-Connecting-IP` in an earlier request
# phase — POST_READ, against ACCESS. So by the time an `allow 173.245.48.0/20;`
# is evaluated, `$remote_addr` is no longer the Cloudflare edge that connected,
# it is the visitor's own address. Every real visitor then fails the test and the
# origin answers 403 to the entire internet while passing `nginx -t`.
#
# Measured on this setup rather than reasoned about: through the edge,
# `$remote_addr` read 68.189.186.165 (the visitor) while `$realip_remote_addr`
# read 172.71.31.157 (the Cloudflare edge).
#
# `$realip_remote_addr` is the address before that rewriting, which is the one
# the question is about. `allow` cannot take a variable; `geo` can, so the ranges
# are emitted as a geo map and the server block tests the flag it sets.
#
# **The generated file holds the ranges and nothing else** — no `default`, no
# local exceptions, no closing rule. Those live in the `geo` block that includes
# it, so that this file being rewritten, truncated or deleted by cron is never
# the same event as locking everybody out. See nginx.conf.example.
#

set -euo pipefail

CLOUDFLARE_FILE_PATH="${1:-/etc/nginx/cloudflare}"
GUARD_FILE_PATH="${2:-/etc/nginx/cloudflare-geo}"

# Cloudflare has published somewhere around twenty ranges for years. This is not
# a guess at the right number, it is a floor: a truncated download or a
# reformatted endpoint should stop the script rather than quietly narrow the set
# of addresses nginx will accept, which is a lockout.
MIN_EXPECTED_RANGES=10

ipv4="$(curl -fsSL https://www.cloudflare.com/ips-v4)"
ipv6="$(curl -fsSL https://www.cloudflare.com/ips-v6)"

# Fetched once into variables rather than curled per output file, so the two
# files cannot disagree because the list changed between two requests.
ranges="$(printf '%s\n%s\n' "$ipv4" "$ipv6" | grep -c '[^[:space:]]')"

if [[ "$ranges" -lt "$MIN_EXPECTED_RANGES" ]]; then
    echo "Refusing to write: only $ranges Cloudflare ranges fetched, expected at least $MIN_EXPECTED_RANGES" >&2
    exit 1
fi

real_ip_tmp="$(mktemp)"
guard_tmp="$(mktemp)"
trap 'rm -f "$real_ip_tmp" "$guard_tmp"' EXIT

# Trust the forwarded client address from these, and nothing else.
{
    echo "# Cloudflare — generated by cloudflare-sync-ips.sh, do not edit"
    echo ""
    echo "# - IPv4"
    printf '%s\n' "$ipv4" | grep '[^[:space:]]' | while read -r ip; do
        echo "set_real_ip_from $ip;"
    done

    echo ""
    echo "# - IPv6"
    printf '%s\n' "$ipv6" | grep '[^[:space:]]' | while read -r ip; do
        echo "set_real_ip_from $ip;"
    done

    echo ""
    echo "real_ip_header CF-Connecting-IP;"
} > "$real_ip_tmp"

# The same ranges as `geo` map entries. Ranges only — the `default`, the local
# exceptions and the enclosing block belong to whoever includes this.
{
    echo "# Cloudflare — generated by cloudflare-sync-ips.sh, do not edit"
    echo "#"
    echo "# Include inside a geo block keyed on \$realip_remote_addr, which is the"
    echo "# peer address before the realip module rewrites it. See nginx.conf.example."
    echo ""
    echo "# - IPv4"
    printf '%s\n' "$ipv4" | grep '[^[:space:]]' | while read -r ip; do
        echo "$ip 1;"
    done

    echo ""
    echo "# - IPv6"
    printf '%s\n' "$ipv6" | grep '[^[:space:]]' | while read -r ip; do
        echo "$ip 1;"
    done
} > "$guard_tmp"

# Keep what is currently in place, so a configuration this breaks can be undone
# before nginx is asked to run with it.
previous_real_ip="$(mktemp)"
previous_guard="$(mktemp)"
trap 'rm -f "$real_ip_tmp" "$guard_tmp" "$previous_real_ip" "$previous_guard"' EXIT
[[ -f "$CLOUDFLARE_FILE_PATH" ]] && cp -a "$CLOUDFLARE_FILE_PATH" "$previous_real_ip"
[[ -f "$GUARD_FILE_PATH" ]] && cp -a "$GUARD_FILE_PATH" "$previous_guard"

install -m 0644 "$real_ip_tmp" "$CLOUDFLARE_FILE_PATH"
install -m 0644 "$guard_tmp" "$GUARD_FILE_PATH"

# Test, and put the old files back if the new ones do not survive it. Reloading
# is the easy half; the half worth writing down is that a bad guard list is an
# outage, so it never gets as far as a running nginx.
if ! nginx -t; then
    echo "nginx rejected the generated files; restoring the previous ones" >&2
    [[ -s "$previous_real_ip" ]] && install -m 0644 "$previous_real_ip" "$CLOUDFLARE_FILE_PATH"
    [[ -s "$previous_guard" ]] && install -m 0644 "$previous_guard" "$GUARD_FILE_PATH"
    exit 1
fi

systemctl reload nginx
